name: Run better-crowdin
description: This action allows you to manage and synchronize localization resources with your Crowdin project, using `better-crowdin` CLI
author: ardeois
inputs:
  action:
    description: Action to run ('delbranch', 'download', 'upload sources', 'upload translations', 'sync')
    required: false
    default: 'upload sources'
  config:
    description: Crowdin configuration file path [crowdin.yml]
    required: false
  branch:
    description: Crowdin branch to use with command (defaults to current ref from github event `github.event.ref`).
    required: false
    default: ${{github.event.ref}}
  dry_run:
    description: Do not execute write operations on crowdin
    required: false
    default: 'false'
  relative_path:
    description: Make "base_path" property relative to config file path
    required: false
    default: 'false'
  porcelain:
    description: Print script-aware outputs (no colors, no human friendly info)
    required: false
    default: 'false'
  ignore_errors:
    description: Ignore any script error. This could be useful for `delbranch` in case the branch does not exists
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
branding:
  icon: refresh-cw
  color: blue
