name: Run better-crowdin
description: This action allows you to manage and synchronize localization resources with your Crowdin project, using `better-crowdin` CLI
author: ardeois
inputs:
  action:
    description: Action to run ('delbranch', 'download', 'upload sources', 'upload translations', 'sync')
    required: false
    default: 'upload sources'
  branch:
    description: Crowdin branch to use with command (defaults to current git branch). Note this is required when you use action 'delbranch')
    required: false
  dry-run:
    description: Do not execute write operations on crowdin
    required: false
    default: 'false'
  relative-path:
    description: Make "base_path" property relative to config file path
    required: false
    default: 'false'
  porcelain:
    description: Print script-aware outputs (no colors, no human friendly info)
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
branding:
  icon: circle
  color: purple
